Resolved merge conflict.

diff --git a/pi-firmware/debug b/pi-firmware/debug
--- a/pi-firmware/debug
+++ b/pi-firmware/debug
@@ -8,6 +8,16 @@ VERSION="0.1.$(echo "$(<"version")" | tr -d '[:space:]')"
 # Define source and destination folders
 LOCAL_SOURCE_FOLDER="./"
 USER="pi"
+
+if [ ! -e "$file_path" ]; then
+    echo "WARNING: No target found! Creating fallback target, raspberrypi.local <- this only works with the bonjour service!"
+    echo "rapberrypi.local" > target
+    # Continue with your script logic here
+else
+    echo "Error: File not found: $file_path"
+    exit 1  # Exit the script with an error status
+fi
+
 HOST="$(<"target")"
 
 ### TODO: make this UNIVERSAL
@@ -29,12 +39,16 @@ NAT_IP=$(ip route get 1 | awk '{print $7}')
 DEBUG_PORT=5678
 
 # For debug mode, run ./debug 1
-if [ "$1" -eq 1 ]; then
+if [ "$1" -eq "1" ]; then
     RUNNER="-m debugpy --listen 0.0.0.0:$DEBUG_PORT --wait-for-client"
 fi
 
 ssh $USER@$HOST "mkdir -p $TARGET && tar -xzvf - -C $TARGET && \
-    cd $TARGET && stop; killall python3; echo "Waiting for Debugger to connect on $NAT_IP:$DEBUG_PORT" && \
+    cd $TARGET && stop; killall python3; \
+    echo "--- Waiting for Debugger to connect on $NAT_IP:$DEBUG_PORT ---\n" && \
+    echo "- do not forget to set your launch.json to the proper target! -" \n\n && \
     python3 $RUNNER ./revvy.py" < $PACKAGE_SOURCE
+
+
 ##
 #ssh $USER@$HOST "cd Revvy python -m debugpy --listen 5678 --wait-for-client ./revvy.py"
